### ISSUE TITLE
Faltando arquivo no repositório

### ISSUE THREAD

**Issue by rodrigoclira** [Leonardo-acs/projeto_loja_de_acai.py#1]
Não encontrei esse módulo que é importado no arquivo principal do projeto. 

https://github.com/Leonardo-acs/projeto_loja_de_acai.py/blob/ad4b8085a33becb9cf6ab2f070155d85d5e5d0fd/projeto_loja_de_a%C3%A7ai.py#L2

**Comment by Leonardo-acs** [comment]
@rodrigoclira  Rodrigo, já entendi qual foi o problema, quando eu importei para o github eu alterei o nome dos arquivos. (Comandos_projetos seria em relação a "comandos_projeto_loja_de_acai_") e projeto loja de açaí seria em relação a projeto final.

**Comment by Leonardo-acs** [comment]
@rodrigoclira  Alterei o nome dos projetos, acredito que agora vai

**Comment by Leonardo-acs** [comment]
@rodrigoclira O sr roda o projeto pelo que tem nome "comandos_projetos"
